version: "3"
services:
  oauth-service-ott:
    build: .
    command: --auth_profile=ott
    ports:
      - "9090:9090"

  oauth-service-mvpd:
    build: .
    command: --auth_profile=mvpd
    ports:
      - "9095:9090"
