version: "3"
services:
  oauth-service-mvpd:
    image: oauth-service-app:latest
    command: --auth_profile=mvpd
    network_mode: bridge
    container_name: oauth-service-mvpd
    expose:
      - 9090
    ports:
      - 9090:9090

  oauth-service-ott:
    image: oauth-service-app:latest
    command: --auth_profile=ott
    network_mode: bridge
    container_name: oauth-service-ott
    expose:
      - 9091
    ports:
      - 9091:9090
